### ISSUE TITLE
having issues running migrations on a fresh install

### ISSUE THREAD

**Issue by sam2332** [django-cms/djangocms-versioning#361]
python manage.py migrate djangocms_versioning

nty$ python manage.py makemigrations
Traceback (most recent call last):
  File "{folder}/InghamCounty/manage.py", line 22, in <module>
    main()
  File "{folder}/InghamCounty/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "{folder}/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "{folder}/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "{folder}/env/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "{folder}/env/lib/python3.10/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "{folder}/env/lib/python3.10/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "{folder}/env/lib/python3.10/site-packages/djangocms_versioning/models.py", line 13, in <module>
    from .conditions import (
  File "{folder}/env/lib/python3.10/site-packages/djangocms_versioning/conditions.py", line 7, in <module>
    from .helpers import get_latest_draft_version, version_is_unlocked_for_user
  File "{folder}/env/lib/python3.10/site-packages/djangocms_versioning/helpers.py", line 6, in <module>
    from cms.models import Page, PageContent, Placeholder
ImportError: cannot import name 'PageContent' from 'cms.models' ({folder}/env/lib/python3.10/site-packages/cms/models/__init__.py)

**Comment by fsbraun** [comment]
@sam2332 What versions of django CMS and Django are you running?

**Comment by sam2332** [comment]
@fsbraun 
Thank you for responding here are the versions


```
Name: Django
Version: 4.2.7
Summary: A high-level Python web framework that encourages rapid development and clean, pragmatic design.
Home-page: https://www.djangoproject.com/
Author: Django Software Foundation
Author-email: foundation@djangoproject.com
License: BSD-3-Clause
Location: /home/srudloff/InghamCountyDjangoWebsite/env/lib/python3.10/site-packages
Requires: asgiref, sqlparse
Required-by: django-bootstrap4, django-classy-tags, django-cms, django-filer, django-formtools, django-polymorphic, django-scheduler, django-sekizai, django-storages, django-treebeard, djangocms-admin-style, djangocms-versioning, djangorestframework, easy-thumbnails
```



```
Name: django-cms
Version: 3.11.4
Summary: Lean enterprise content management powered by Django.
Home-page: https://www.django-cms.org/
Author: Django CMS Association and contributors
Author-email: info@django-cms.org
License: BSD-3-Clause
Location: /home/srudloff/InghamCountyDjangoWebsite/env/lib/python3.10/site-packages
Requires: Django, django-classy-tags, django-formtools, django-sekizai, django-treebeard, djangocms-admin-style, packaging
Required-by: djangocms-attributes-field, djangocms-file, djangocms-link, djangocms-picture, djangocms-style, djangocms-text-ckeditor, djangocms-versioning
```

**Comment by sam2332** [comment]
if you dont mind me asking, what version is considered stable with your release cycle?

**Comment by fsbraun** [comment]
**djangocms-versioning only works with django CMS v4+**. The latest stable version is django CMS 3.11.4 which has long-term support until April 2026. For more see https://docs.django-cms.org/
